alias: Turn off lights at 10:30pm during the week
trigger:
  platform: time
  at: '22:30:00'
condition:
  condition: time
  weekday:
    - sun
    - mon
    - tue
    - wed
    - thu
action:
  service: homeassistant.turn_off
  entity_id: group.living_room
