alias: Turn off lights at 11:45pm during the weekend
trigger:
  platform: time
  at: '23:45:00'
condition:
  condition: time
  weekday:
    - fri
    - sat
action:
  service: homeassistant.turn_off
  entity_id: group.living_room
