#### SUN BASED ####
- !include automations/sunset_livingroom_lights.yaml

#### TIME BASED ####
- !include automations/time_weekday_livingroom_lights_off.yaml
- !include automations/time_weekend_livingroom_lights_off.yaml
