#### SUN BASED ####
- !include automation/sunset_livingroom_lights.yaml

#### TIME BASED ####
- !include automation/time_weekday_livingroom_lights_off.yaml
- !include automation/time_weekend_livingroom_lights_off.yaml
