http_password: password
location_latitude: 000.0000000
location_longitude: 000.0000000
location_time_zone: America/Phoenix
ecobee_api: 0000000000
sleepiq_username: username
sleepiq_password: password
hue_host_ip: 127.0.0.1